# Sandbox settings
BOWER_ROOT = "vendor/assets/bower_components/"
SANDBOX_ROOT = "#{BOWER_ROOT}behavior_ui/"
SANDBOX_DOCS_ROOT = "#{SANDBOX_ROOT}sandbox/"
SANDBOX_DOCS_PATH = "docs/"
SANDBOX_DOCS_ABOUT = "#{SANDBOX_DOCS_ROOT}about/"
SANDBOX_DOCS_FULL_PATH = "#{SANDBOX_DOCS_ROOT}#{SANDBOX_DOCS_PATH}"
